from .ai_analyzer import PRAnalysis
from .github_client import PRData

CHANGE_TYPE_EMOJI = {
    "feat": "✨",
    "fix": "🐛",
    "refactor": "♻️",
    "chore": "🔧",
    "docs": "📝",
    "test": "🧪",
    "perf": "⚡",
}


def format_pr_comment(pr: PRData, analysis: PRAnalysis) -> str:
    """Build a rich Markdown comment for the PR."""
    emoji = CHANGE_TYPE_EMOJI.get(analysis.change_type, "🔀")
    lines = []

    # Header
    lines.append("## 🤖 AI PR Summary")
    lines.append("")
    lines.append(
        f"> Generated by [ai-pr-summarizer](https://github.com/your-username/ai-pr-summarizer)"
    )
    lines.append("")

    # Change type badge
    lines.append(
        f"**Type:** {emoji} `{analysis.change_type}`&nbsp;&nbsp;"
        f"**Files:** `{len(pr.files_changed)}`&nbsp;&nbsp;"
        f"**Changes:** `+{pr.additions} / -{pr.deletions}`"
    )
    lines.append("")

    # Suggested title
    lines.append("### 💡 Suggested Title")
    lines.append(f"```")
    lines.append(analysis.suggested_title)
    lines.append("```")
    lines.append("")

    # Summary
    lines.append("### 📋 Summary")
    lines.append(analysis.summary)
    lines.append("")

    # Files overview
    lines.append("### 📁 Files Overview")
    lines.append(analysis.files_overview)
    lines.append("")

    # Breaking changes
    if analysis.breaking_changes:
        lines.append("### 💥 Breaking Changes")
        for change in analysis.breaking_changes:
            lines.append(f"- ⚠️ {change}")
        lines.append("")

    # Risks
    if analysis.risks:
        lines.append("### 🔍 Potential Risks")
        for risk in analysis.risks:
            lines.append(f"- {risk}")
        lines.append("")
    else:
        lines.append("### ✅ Risks")
        lines.append("No significant risks detected.")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append(
        "_This summary was generated automatically. "
        "Please verify before merging._"
    )

    return "\n".join(lines)


def format_cli_output(pr: PRData, analysis: PRAnalysis) -> str:
    """Format analysis for terminal output."""
    sep = "─" * 60
    lines = [
        "",
        sep,
        f"  🤖  AI PR SUMMARY  —  {pr.repo} #{pr.pr_number}",
        sep,
        "",
        f"  💡 Suggested Title:",
        f"     {analysis.suggested_title}",
        "",
        f"  📋 Summary:",
    ]
    for sentence in analysis.summary.split(". "):
        if sentence:
            lines.append(f"     {sentence.strip()}.")
    lines.append("")
    lines.append(f"  📁 Files Overview:")
    lines.append(f"     {analysis.files_overview}")
    lines.append("")

    if analysis.breaking_changes:
        lines.append(f"  💥 Breaking Changes:")
        for c in analysis.breaking_changes:
            lines.append(f"     ⚠️  {c}")
        lines.append("")

    if analysis.risks:
        lines.append(f"  🔍 Risks:")
        for r in analysis.risks:
            lines.append(f"     • {r}")
    else:
        lines.append(f"  ✅ No significant risks detected.")

    lines += ["", sep, ""]
    return "\n".join(lines)
